// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0DNV_xap_xwVWVr30nyFZyU00wAWq38',
    appId: '1:1082660313251:web:27829ade11bb7af04a0716',
    messagingSenderId: '1082660313251',
    projectId: 'manong-f8ca4',
    authDomain: 'manong-f8ca4.firebaseapp.com',
    databaseURL: 'https://manong-f8ca4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'manong-f8ca4.firebasestorage.app',
    measurementId: 'G-QS8X4RPS3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YAEjghqFM4JEzp63zsbzdd0Mpo7ULqA',
    appId: '1:1082660313251:android:ce84eaddf3153f7e4a0716',
    messagingSenderId: '1082660313251',
    projectId: 'manong-f8ca4',
    databaseURL: 'https://manong-f8ca4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'manong-f8ca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApE2QO1TzkBGB4KBqL0mvIWKvnSNNtqCk',
    appId: '1:1082660313251:ios:b24ed977df6f173a4a0716',
    messagingSenderId: '1082660313251',
    projectId: 'manong-f8ca4',
    databaseURL: 'https://manong-f8ca4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'manong-f8ca4.firebasestorage.app',
    androidClientId: '1082660313251-0bl875gq7rl1qv7s06orbmhei0aavak0.apps.googleusercontent.com',
    iosBundleId: 'com.manong.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApE2QO1TzkBGB4KBqL0mvIWKvnSNNtqCk',
    appId: '1:1082660313251:ios:c02ddc26596c6c834a0716',
    messagingSenderId: '1082660313251',
    projectId: 'manong-f8ca4',
    databaseURL: 'https://manong-f8ca4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'manong-f8ca4.firebasestorage.app',
    androidClientId: '1082660313251-0bl875gq7rl1qv7s06orbmhei0aavak0.apps.googleusercontent.com',
    iosBundleId: 'com.example.manongApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ0DNV_xap_xwVWVr30nyFZyU00wAWq38',
    appId: '1:1082660313251:web:0f6cebfdbedd97654a0716',
    messagingSenderId: '1082660313251',
    projectId: 'manong-f8ca4',
    authDomain: 'manong-f8ca4.firebaseapp.com',
    databaseURL: 'https://manong-f8ca4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'manong-f8ca4.firebasestorage.app',
    measurementId: 'G-VB34VJNWYQ',
  );
}
